# Generated by Django 3.0.5 on 2021-02-06 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20210207_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='foot',
            field=models.CharField(choices=[('Правая', 'правая'), ('Левая', 'левая'), ('Обе', 'обе')], max_length=150, verbose_name='Рабочая нога'),
        ),
    ]
