# Generated by Django 3.0.5 on 2021-02-07 10:36

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_auto_20210207_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-price'], 'verbose_name': 'Футболисты', 'verbose_name_plural': 'Футболисты'},
        ),
        migrations.RenameField(
            model_name='player',
            old_name='assists',
            new_name='assists_chempionship',
        ),
        migrations.AddField(
            model_name='player',
            name='assists_cup',
            field=models.IntegerField(default=0, verbose_name='Голевые в кубке'),
        ),
        migrations.AddField(
            model_name='player',
            name='assists_international',
            field=models.IntegerField(default=0, verbose_name='голевые в еврокубках'),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_cup',
            field=models.IntegerField(default=0, verbose_name='Голы в кубке'),
        ),
        migrations.AddField(
            model_name='player',
            name='goals_international',
            field=models.IntegerField(default=0, verbose_name='Голы в еврокубках'),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_cup',
            field=models.IntegerField(default=0, verbose_name='Матчи в кубке'),
        ),
        migrations.AddField(
            model_name='player',
            name='matches_international',
            field=models.IntegerField(default=0, verbose_name='Матчи в еврокубках'),
        ),
        migrations.AddField(
            model_name='player',
            name='national_assists',
            field=models.IntegerField(default=0, verbose_name='голевые за сборную'),
        ),
        migrations.AddField(
            model_name='player',
            name='national_goals',
            field=models.IntegerField(default=0, verbose_name='голы за сборную'),
        ),
        migrations.AddField(
            model_name='player',
            name='national_matches',
            field=models.IntegerField(default=0, verbose_name='Матчи за сборную'),
        ),
        migrations.AlterField(
            model_name='player',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=1, default_currency='USD', max_digits=14, verbose_name='Цена в Transfermarkt'),
        ),
    ]
