# Generated by Django 3.0.5 on 2021-02-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20210207_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cup_name',
            field=models.CharField(default='', max_length=150, verbose_name='Кубок'),
        ),
        migrations.AddField(
            model_name='player',
            name='international_cup',
            field=models.CharField(default='', max_length=150, verbose_name='Международный турнир'),
        ),
    ]
