# Generated by Django 3.0.5 on 2021-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_auto_20210207_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chempionship',
            field=models.CharField(blank=True, max_length=150, verbose_name='Чемпионат'),
        ),
        migrations.AlterField(
            model_name='player',
            name='cup_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Кубок'),
        ),
        migrations.AlterField(
            model_name='player',
            name='international_cup',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Международный турнир'),
        ),
    ]
